//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqAdd
    {
        public int ExtrasId { get; set; }
        public Nullable<long> RequisitionId { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date_Ordered { get; set; }
        public string CC_Holder_Name { get; set; }
        public string Purchase_Order_Num { get; set; }
        public Nullable<System.DateTime> Date_Expected_Delivery { get; set; }
    
        public virtual Requisition Requisition { get; set; }
    }
}
