//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.Items = new HashSet<Item>();
            this.ReqAdds = new HashSet<ReqAdd>();
        }
    
        public long RequisitionId { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Requisitioned_By { get; set; }
        public string Explanation { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Decision_By { get; set; }
        public WebApplication9.Data.Helpers.StatusEnum Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> CFO_approval { get; set; }
        public string CFO_Explanation { get; set; }
        public string CFO_Decision_By { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqAdd> ReqAdds { get; set; }
        public virtual User User { get; set; }
    }
}
